# Generated by Django 4.1.2 on 2024-07-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nav_delivery',
            fields=[
                ('id_nav_delivery', models.AutoField(db_column='idNavdelivery', primary_key=True, serialize=False)),
                ('nav_delivery', models.CharField(max_length=20)),
                ('url_delivery', models.CharField(default='default_value', max_length=100)),
            ],
        ),
    ]
