# Generated by Django 4.1.2 on 2024-07-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nav_cliente',
            fields=[
                ('id_nav_cliente', models.AutoField(db_column='idNavcliente', primary_key=True, serialize=False)),
                ('nav_cliente', models.CharField(max_length=20)),
                ('url_cliente', models.CharField(default='default_value', max_length=100)),
            ],
        ),
    ]
