# Generated by Django 4.1.2 on 2024-07-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nav_home',
            fields=[
                ('id_nav_home', models.AutoField(db_column='idNavhome', primary_key=True, serialize=False)),
                ('nav_home', models.CharField(max_length=20)),
            ],
        ),
    ]
