# Generated by Django 4.1.2 on 2024-07-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav_home',
            name='url_home',
            field=models.CharField(default='default_value', max_length=20),
        ),
    ]
