# Generated by Django 4.1.2 on 2024-07-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informacion_proveedores',
            fields=[
                ('id_informacion', models.AutoField(db_column='idInformacion', primary_key=True, serialize=False)),
                ('nom_proveedor', models.CharField(max_length=50)),
                ('direccion_proveedor', models.CharField(max_length=100)),
                ('numero_proveedor', models.CharField(max_length=20)),
                ('tipo_servicio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nav_proveedores',
            fields=[
                ('id_navbar', models.AutoField(db_column='idNavProveedores', primary_key=True, serialize=False)),
                ('nav_proveedores', models.CharField(max_length=20)),
                ('url_proveedores', models.CharField(default='default_value', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Platos_proveedores',
            fields=[
                ('id_platos', models.AutoField(db_column='idPlatos', primary_key=True, serialize=False)),
                ('nom_platos', models.CharField(max_length=50)),
                ('precio_platos', models.CharField(max_length=20)),
                ('oferta_platos', models.CharField(max_length=20)),
                ('detalles_platos', models.CharField(max_length=100)),
            ],
        ),
    ]
